apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: example-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/<PROJECT_ID>/locations/<REGION>/clusters/<CLUSTER_NAME>
