name: proxy-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'  # Update to your specific directory
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Service Account Key File
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | base64 --decode > $HOME/gcloud-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: $HOME/gcloud-key.json
          export_default_credentials: true

      - name: Authenticate to GCP
        run: gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

      - name: Create API bundle
        run: zip -r proxy.zip your-directory/apiproxy  # Update path if needed

      - name: Upload API Proxy Bundle
        id: upload
        run: |
          apigee_revision=$(curl --fail -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F "file=@proxy.zip" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/apis?action=import&name=hello-world" \
          --silent | jq --raw-output .revision)
          echo "::set-output name=apigee-revision::$apigee_revision"

      - name: Deploy Revision
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          "https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/eval/apis/hello-world/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments?override=true"
