name: Deploy to Apigee

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy API to Apigee
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      APIGEE_ORG: ${{ secrets.APIGEE_ORG }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Authenticate to GCP
        run: gcloud auth activate-service-account --key-file="${{ env.SERVICE_ACCOUNT_KEY }}"

      - name: Create API Bundle
        run: zip -r proxy.zip apiproxy  # Adjust path if needed

      - name: Upload API Proxy Bundle to Apigee
        id: upload
        run: |
          apigee_revision=$(curl --fail -X POST \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F "file=@proxy.zip" \
          "https://apigee.googleapis.com/v1/organizations/${APIGEE_ORG}/apis?action=import&name=my-api-proxy" \
          --silent | jq --raw-output .revision)
          echo "::set-output name=apigee-revision::$apigee_revision"

      - name: Deploy API Proxy to Apigee
        run: |
          curl --fail -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          "https://apigee.googleapis.com/v1/organizations/${APIGEE_ORG}/environments/test/apis/my-api-proxy/revisions/${{ steps.upload.outputs.apigee-revision }}/deployments?override=true"
